-- Rename existing Role enum values
ALTER TYPE "Role" RENAME VALUE 'ALUNO' TO 'STUDENT';
ALTER TYPE "Role" RENAME VALUE 'COORDENADOR' TO 'ASSISTANT';
ALTER TYPE "Role" RENAME VALUE 'ADMIN' TO 'ADMINISTRATOR';
ALTER TYPE "Role" RENAME VALUE 'SUPER_ADMIN' TO 'OWNER';
ALTER TYPE "Role" RENAME VALUE 'RESPONSAVEL' TO 'RESPONSIBLE';

-- Add new value
ALTER TYPE "Role" ADD VALUE 'TI_SUPPORT';
